# This is a basic workflow to help you get started with Actions

name: Update JAR(s) - 1.20.6

# Controls when the workflow will run - only when modifying pack or pushing changes etc
#on:
#  push:
#    branches:
#      - main
#  schedule:
#    - cron: '0 */12 * * *'


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:



# -----------------------------------------
# Build datapacks
# -----------------------------------------





  # Build the root pack
  main-thrd:
    runs-on: ubuntu-latest
  #  needs: [validate_main]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Get latest version
        run: |
         curl -L https://api.nikostuff.com/v1/latest_jar?download -o server_u.jar

         
      - name: Upload JAR
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
            username: ${{ secrets.SFTP_user }}
            server: ${{ secrets.SFTP_ip }}
            port: 2022
            local_path: './server_u.jar'
            remote_path: '/'
            sftp_only: true
            password: ${{ secrets.SFTP_pass }}
